apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xmkl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xmkl
    app.kubernetes.io/part-of: tkrw-pr714-0075-0070-app
  name: devfile-sample-xmkl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xmkl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xmkl
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0070-tenant/tkrw-pr714-0075-0070-app/devfile-sample-xmkl@sha256:a7e341283e0afb1c0153db63aa100cbed48cd1ac0e5fc2e703ddbc7ca845c779
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
